<a href="https://colab.research.google.com/github/OldLady2/LittleThings/blob/master/PTwC(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

###LISTS

In [3]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [4]:
my_list2 = [[1, 2, 3, 4, 5], [6, 7, 8,9, 10]]
my_list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

### NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3, 4)
np1

array([[0.48970256, 0.30205714, 0.93690819, 0.84998564],
       [0.67441665, 0.70267398, 0.17616466, 0.78904498],
       [0.13027423, 0.21761764, 0.43694164, 0.02055161]])

In [6]:
np1.dtype

dtype('float64')

### TENSORS

In [13]:
tensor_2d = torch.randn(3, 4)
tensor_2d


tensor([[ 0.0172,  0.7165, -1.2634, -0.8578],
        [ 0.5276, -1.0285, -1.0413,  0.2544],
        [ 0.2559, -1.0661, -0.9100, -0.7511]])

In [14]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
tensor_3d2 = torch.randn(2, 3, 4)
tensor_3d2

tensor([[[-0.3799, -0.6151,  0.1570,  0.7740],
         [ 0.2256, -0.8288,  0.5380, -0.1229],
         [-0.1477,  1.4116,  1.7872,  0.5148]],

        [[ 1.5031, -0.6576,  0.7113,  1.8878],
         [ 0.0573, -0.1834, -0.8271,  0.7707],
         [ 0.2333, -0.2325, -1.2424, -1.5969]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4897, 0.3021, 0.9369, 0.8500],
        [0.6744, 0.7027, 0.1762, 0.7890],
        [0.1303, 0.2176, 0.4369, 0.0206]], dtype=torch.float64)