<a href="https://colab.research.google.com/github/OldLady2/LittleThings/blob/master/Torch4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Doing basic mathematical operations with pytorch.

In [5]:
import torch
import numpy as np
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


Addition, two ways.

In [9]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [10]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

Subtraction. As a function, sub.

In [11]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

Multiplication. As a function, mul.

In [13]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [14]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

Division, as div.

In [21]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

Get the remainder from the modulus function.

In [22]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

Asking for the remainder, as such.

In [23]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

Activating an exponential function, pow.

In [24]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

Adding one tensor unto another.

In [36]:
tensor_c = torch.tensor([1,2,3,4])
tensor_c

tensor([1, 2, 3, 4])

tensor_a now has the new value...

In [37]:
tensor_c.add(tensor_b)

tensor([ 6,  8, 10, 12])

Reassignment. The first tensor keeps the new value.

In [50]:
tensor_d =torch.tensor([1, 2, 3, 4])
tensor_d.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [51]:
tensor_d

tensor([ 6,  8, 10, 12])